// Snapshot the official default palette once so runtime CSP can stay style-src 'self'.
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../docs/vendor/framework7');
(async () => {
  const browser = await chromium.launch({headless:true});
  try {
    const page = await browser.newPage();
    await page.setContent('<html><body><div id="app"></div></body></html>');
    await page.addScriptTag({path:path.join(root,'framework7-bundle.min.js')});
    const css = await page.evaluate(() => {
      new Framework7({el:'#app',theme:'ios'});
      return [...document.querySelectorAll('style')].map(x=>x.textContent).join('\n');
    });
    if (!css.includes('--f7-color-primary')) throw new Error('Official palette was not generated');
    fs.writeFileSync(path.join(root,'framework7-default-theme.css'), '/* Generated by unmodified Framework7 9.1.3 defaults; do not edit. */\n'+css);
    console.log('Saved the unmodified Framework7 default palette: '+css.length+' characters');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
