// Fully intercepted fixtures: no real subscription or network changes.
const {chromium}=require('../frontend/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ui=path.resolve(__dirname,'../src/server_network_assist/subscription_admin_ui');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),posts=[],errors=[];
 let auth=false,fail=false,proxy=false;
 const now=Math.floor(Date.now()/1000),source={id:'s0',name:'校园物理源网',endpoint:'10.20.32.13:51910',egress_mode:'physical',egress_interface:'eth0',egress_gateway:'10.20.32.1'};
 const customers=[0,1,2].map(i=>({id:'c'+i,display_name:i===0?'测试月租':'长名称'.repeat(30)+i,enabled:true,version:0,revision:'r'+i,usable:i===0,reasons:i===1?['额度用完']:i===2?['源机代理未就绪']:[],active_lease_count:i===0?1:0,
 plan:{quota_bytes:10*1024**3,download_bps:50000000,upload_bps:10000000,max_devices:2,period_seconds:2592000},
 usage:{used_bytes:(i===1?10:1)*1024**3,quota_bytes:10*1024**3,remaining_bytes:i===1?0:9*1024**3,period_end:now+2592000,today_bytes:100,total_bytes:1024**3,last_report_at:now,measurement_status:'fresh',download_bytes_per_second:1000,upload_bytes_per_second:100},
 grants:[{id:'g'+i,source_id:'s0',source_name:source.name,name:'线路',endpoint:source.endpoint,enabled:true,egress_mode:i===2?'source_proxy':'physical',expires_at:now+2592000,proxy_ready:false,reasons:[]}],devices:[{id:'d'+i,label:'设备',enabled:true,created_at:now}],leases:[],history:[],usage_periods:[]}));
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async r=>{const q=r.request(),url=new URL(q.url());assert.equal(url.hostname,'dashboard-fixture.test');const name=url.pathname.split('/').at(-1);
  if(!url.pathname.includes('/api/'))return r.fulfill({body:fs.readFileSync(path.join(ui,name)),contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html'});
  const api=url.pathname.split('/api/')[1],body=q.postDataJSON();if(q.method()==='POST')posts.push({api,body});let data={};
  if(api==='session')data={authenticated:auth,csrf:'fixture'};
  else if(api==='login'){auth=true;data={authenticated:true,csrf:'fixture'};}
  else if(api==='logout'){auth=false;}
  else if(api==='client-service')data={sources:[source],customers,subscription_addresses:customers.map(c=>({customer_id:c.id,status:'used',available:true,used_at:now,device_count:1,max_devices:2})),source_proxy:{available:proxy,reason:'未启动'}};
  else if(api==='client-service/dashboard'){if(fail)return r.fulfill({status:503,json:{error:'fixture failure'}});customers.forEach(c=>c.grants.forEach(g=>g.proxy_ready=proxy));data={generated_at:now,accounting_day:'2026-09-17',accounting_timezone:'UTC+8',measurement_note:'实际中继计量',customers,summary:{customers:3,usable:1,active_leases:1,today_bytes:300,total_bytes:3*1024**3}};}
  else if(api==='client-service/action'){assert.equal(q.headers()['x-csrf-token'],'fixture');if(body.action==='subscription-update'){const c=customers.find(c=>c.id===body.id);for(const k of ['quota_bytes','download_bps','upload_bps'])if(k in body.service)c.plan[k]=body.service[k];Object.assign(c.usage,{quota_bytes:c.plan.quota_bytes,remaining_bytes:c.plan.quota_bytes==null?null:Math.max(0,c.plan.quota_bytes-c.usage.used_bytes)});if('expires_at' in body.service)c.grants.forEach(g=>g.expires_at=body.service.expires_at);if(body.service.grants)Object.assign(c.grants[0],body.service.grants[0]);for(const k of ['tags','notes','lifecycle'])if(k in body.service)c[k]=body.service[k];if(c.lifecycle&&c.lifecycle!=='active'){c.enabled=false;c.usable=false;c.active_lease_count=0;}c.version++;c.revision='updated';data={ok:true,reconnect_required:true,subscription_address_changed:false,usage_reset:false};}else if(body.action==='device-enable'){const d=customers.flatMap(c=>c.devices).find(d=>d.id===body.id);assert.ok(d);d.enabled=body.enabled;data={ok:true};}else throw Error('Unexpected mutation '+body.action);}
  else throw Error(api);return r.fulfill({json:data});
 });
 await page.goto('http://dashboard-fixture.test/subscriptions.html');await page.locator('#login-panel').waitFor();
 await page.locator('#login-form [name=key]').fill('fixture-only');await page.locator('#login-form button[type=submit]').click();await page.locator('#dashboard-rows tr[data-customer-id]').first().waitFor();
 assert.equal(await page.locator('#dashboard-rows tr[data-customer-id]').count(),3);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.equal(await page.locator('#manager').isVisible(),false);assert.equal(await page.locator('#egress-panel').isVisible(),false);assert.equal(await page.locator('#dashboard-rows tr[data-customer-id=c0] td').count(),6);
 const beforeNav=posts.length;await page.locator('#nav-generate').click();await page.locator('#manager').waitFor();await page.locator('#nav-egress').click();await page.locator('#egress-panel').waitFor();await page.locator('#nav-customers').click();assert.equal(posts.length,beforeNav,'Navigation must not mutate service');
 const beforeView=posts.length;await page.locator('#dashboard-rows tr[data-customer-id=c0]').getByRole('button',{name:'查看订阅地址',exact:true}).click();await page.locator('#customer-subscription-form').waitFor();assert.equal(posts.length,beforeView);await page.locator('#customer-action-cancel').click();
 await page.locator('#dashboard-filter').selectOption('quota');assert.equal(await page.locator('#dashboard-rows tr[data-customer-id]').count(),1);await page.locator('#dashboard-filter').selectOption('all');await page.locator('#dashboard-search').fill('测试月租');
 await page.getByRole('button',{name:'修改服务',exact:true}).click();assert.equal(await page.locator('#service-grants option[value=source_proxy]').isDisabled(),true);
 await page.locator('[data-service-days="180"]').click();await page.locator('#service-form [name=unlimited_quota]').check();await page.locator('#service-form [name=unlimited_download]').check();await page.locator('#service-form [name=confirmation]').fill('fixture-only');await page.locator('#service-save').click();
 await page.waitForFunction(()=>document.getElementById('message').textContent.includes('原地址和已消费流量保留'));
 let p=posts.filter(p=>p.body.action==='subscription-update').at(-1).body.service;assert.equal(p.quota_bytes,null);assert.equal(p.download_bps,null);assert.equal(p.expected_revision,'r0');assert.ok(Math.abs(p.expires_at-(now+180*86400))<60);assert.equal(customers[0].usage.used_bytes,1024**3);
 await page.getByRole('button',{name:'修改服务',exact:true}).click();
 await page.locator('#service-form [data-speed-preset=unlimited]').click();await page.locator('[data-service-never]').click();
 await page.locator('#service-form [name=confirmation]').fill('fixture-only');await page.locator('#service-save').click();await page.locator('#service-form').waitFor({state:'hidden'});
 p=posts.filter(p=>p.body.action==='subscription-update').at(-1).body.service;assert.equal(p.expires_at,null);assert.equal(p.download_bps,null);assert.equal(p.upload_bps,null);
 await page.getByRole('button',{name:'修改服务',exact:true}).click();await page.locator('#service-form [data-speed-preset=custom]').click();await page.locator('[data-service-days="365"]').click();
 await page.locator('#service-form [name=download_mbps]').fill('34.567');await page.locator('#service-form [name=upload_mbps]').fill('0.123');
 await page.locator('#service-form [name=confirmation]').fill('fixture-only');await page.locator('#service-save').click();await page.locator('#service-form').waitFor({state:'hidden'});
 p=posts.filter(p=>p.body.action==='subscription-update').at(-1).body.service;assert.equal(p.download_bps,34567000);assert.equal(p.upload_bps,123000);assert.ok(Math.abs(p.expires_at-(Date.now()/1000+365*86400))<60);
 proxy=true;await page.locator('#dashboard-refresh').click();await page.getByRole('button',{name:'修改服务',exact:true}).click();await page.locator('#service-form [data-speed-preset=unlimited]').click();await page.locator('#service-grants select').selectOption('source_proxy');await page.locator('#service-form [name=confirmation]').fill('fixture-only');await page.locator('#service-save').click();await page.locator('#service-form').waitFor({state:'hidden'});
 p=posts.filter(p=>p.body.action==='subscription-update').at(-1).body.service;assert.equal(p.grants[0].egress_mode,'source_proxy');assert.equal('expires_at' in p,false);
 const beforeDetails=posts.length;await page.getByRole('button',{name:'详情 / 设备 / 变更记录',exact:true}).click();await page.locator('#service-detail').waitFor();assert.equal(posts.length,beforeDetails,'Opening details must not change services');assert.match(await page.locator('#service-detail-content').textContent(),/下载上限：不限速/);assert.match(await page.locator('#service-detail-content').textContent(),/有效租约/);await page.locator('#service-detail-content input[type=password]').fill('fixture-only');await page.getByRole('button',{name:'确认停用设备',exact:true}).click();await page.waitForFunction(()=>document.getElementById('message').textContent.includes('设备状态已更新'));assert.equal(customers[0].devices[0].enabled,false);assert.equal(posts.filter(p=>p.api==='client-service/action').at(-1).body.id,'d0');await page.getByRole('button',{name:'详情 / 设备 / 变更记录',exact:true}).click();await page.locator('#service-detail-content input[type=password]').fill('fixture-only');await page.getByRole('button',{name:'确认恢复设备',exact:true}).click();await page.waitForFunction(()=>document.getElementById('service-detail').hidden);assert.equal(customers[0].devices[0].enabled,true);
 const manage=async(state,tags='月租，宿舍',notes='客户备注\n<script>只是文本</script>')=>{await page.getByRole('button',{name:'标签 / 备注 / 归档',exact:true}).click();await page.locator('#customer-manage-form [name=tags]').fill(tags);await page.locator('#customer-manage-form [name=notes]').fill(notes);await page.locator('#customer-manage-form [name=lifecycle]').selectOption(state);await page.locator('#customer-manage-form [name=confirmation]').fill('fixture-only');await page.locator('#customer-manage-save').click();await page.waitForFunction(()=>!document.getElementById('customer-manage-dialog').open);await page.waitForFunction(()=>document.getElementById('message').textContent.includes('客户资料与状态已保存'));};
 await manage('active');assert.deepEqual(customers[0].tags,['月租','宿舍']);assert.equal(customers[0].enabled,true);await page.locator('#dashboard-tag').selectOption('tag:月租');assert.equal(await page.locator('#dashboard-rows tr[data-customer-id]').count(),1);await page.locator('#dashboard-rows summary').click();assert.match(await page.locator('#dashboard-rows').textContent(),/<script>只是文本<\/script>/);assert.equal(await page.locator('#dashboard-rows script').count(),0);await page.locator('#dashboard-tag').selectOption('all');await manage('archived');assert.equal(await page.locator('#dashboard-rows tr[data-customer-id]').count(),0);await page.locator('#dashboard-lifecycle').selectOption('archived');assert.equal(await page.getByRole('button',{name:'修改服务',exact:true}).isDisabled(),true);await manage('deleted');assert.equal(await page.locator('#dashboard-rows tr[data-customer-id]').count(),0);await page.locator('#dashboard-lifecycle').selectOption('deleted');await manage('active');assert.equal(customers[0].enabled,false,'Restore must not silently reenable service');await page.locator('#dashboard-lifecycle').selectOption('active');assert.equal(await page.locator('#dashboard-rows tr[data-customer-id]').count(),1);assert.equal(await page.locator('#customer-manage-form [name=confirmation]').inputValue(),'');assert.equal(customers[0].usage.used_bytes,1024**3);
 await page.locator('#dashboard-search').fill('');await page.locator('.dashboard-table').evaluate(e=>e.scrollLeft=0);await page.screenshot({path:path.resolve(__dirname,'../artifacts/subscription-dashboard-sol-1440.png'),fullPage:true});await page.setViewportSize({width:1024,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('.dashboard-table').evaluate(e=>e.scrollWidth>e.clientWidth),true);await page.screenshot({path:path.resolve(__dirname,'../artifacts/subscription-dashboard-sol-390.png'),fullPage:true});
 fail=true;await page.locator('#dashboard-refresh').click();await page.waitForFunction(()=>document.getElementById('dashboard-updated').textContent.includes('刷新失败'));assert.equal(await page.locator('#dashboard-export').isDisabled(),true);assert.equal(await page.getByRole('button',{name:'修改服务',exact:true}).first().isDisabled(),true);
 await page.getByRole('button',{name:'退出登录',exact:true}).click();await page.locator('#login-panel').waitFor();assert.equal(await page.locator('#dashboard-rows tr').count(),0);assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(errors,[]);
 console.log('Dashboard browser passed: filters, quota/duration/proxy edits, unchanged usage, stale-data guard, wrapping and mobile scrolling, logout. No real requests.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
