'use strict';
const $=id=>document.getElementById(id),token=new URLSearchParams(location.hash.slice(1)).get('token')||'';
history.replaceState(null,'',location.pathname);let state=null;
const app=new Framework7({el:'#app',theme:'ios',name:'借网客户端'});
function text(id,value){$(id).textContent=value==null?'—':String(value)}
function bytes(value){if(value==null)return '未知';const units=['B','KB','MB','GB','TB'];let n=value,i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${units[i]}`}
function speed(value){return value==null?'未限制或未公布':bytes(value)+'/s'}
function date(value){return value?new Date(value*1000).toLocaleString():'未公布'}
function notice(value,error=false){const box=$('notice');box.hidden=false;box.textContent=value;box.style.color=error?'#b42318':''}
async function api(path,body){const options={headers:{'X-Client-Token':token}};if(body!==undefined){options.method='POST';options.headers['Content-Type']='application/json';options.headers.Origin=location.origin;options.body=JSON.stringify(body)}const response=await fetch('/api/'+path,options);const value=await response.json();if(!response.ok)throw new Error(value.error||'操作失败');return value}
async function run(fn){try{await fn()}catch(error){notice(error.message,true)}}
function button(label,kind,handler,disabled=false){const value=document.createElement('button');value.type='button';value.className='button '+kind;value.textContent=label;value.disabled=disabled;value.onclick=handler;return value}
function renderLines(lines){$('lines').replaceChildren();for(const line of lines){const article=document.createElement('article');article.className='card line-card';const header=document.createElement('div');header.className='card-header';const title=document.createElement('div');const h=document.createElement('h2');h.textContent=line.name;const sub=document.createElement('p');sub.className='muted mono wrap';sub.textContent=line.id;title.append(h,sub);const badge=document.createElement('span');badge.className='badge '+(line.connected?'color-green':line.available?'color-blue':'color-gray');badge.textContent=line.connected?'已借网':line.available?'可用':'暂停';header.append(title,badge);const content=document.createElement('div');content.className='card-content card-content-padding';const grid=document.createElement('div');grid.className='line-grid';for(const [name,value] of [['下载上限',speed(line.download_bps)],['上传上限',speed(line.upload_bps)],['流量',line.quota_bytes==null?'未公布':`${bytes(line.used_bytes||0)} / ${bytes(line.quota_bytes)}`],['线路到期',date(line.expires_at)],['本机配置',line.installed?'已安装':'未安装'],['最近握手',line.handshake?date(line.handshake):'暂无']]){const cell=document.createElement('div');const span=document.createElement('span');span.textContent=name;const strong=document.createElement('strong');strong.textContent=value;cell.append(span,strong);grid.append(cell)}content.append(grid);const result=document.createElement('p');result.className='muted';result.textContent='尚未检测接入延迟';const actions=document.createElement('div');actions.className='action-row';actions.append(button('检测延迟','button-outline',()=>run(async()=>{const value=await api('line/probe',{id:line.id});result.textContent=value.reachable?`接入点可达，TCP 建连 ${value.latency_ms} ms`:`接入点不可达（${value.reason||'网络错误'}）`;})),button('启动借网','button-fill',()=>run(async()=>{await api('line/connect',{id:line.id});notice('借网已启动，请核对握手和公网状态。');await refresh();}),!line.available||!line.installed||line.connected),button('退出借网','button-outline color-red',()=>run(async()=>{const value=await api('line/disconnect',{id:line.id});notice(value.original_network.ok?'已退出借网，原网络公网探测成功。':'已退出借网；原网络公网探测未通过，请检查校园认证或物理网络。',!value.original_network.ok);await refresh();}),!line.installed||!line.connected));content.append(result,actions);article.append(header,content);$('lines').append(article)}if(!lines.length){const empty=document.createElement('article');empty.className='card';empty.innerHTML='<div class="card-content card-content-padding"><p>当前订阅没有可展示的线路。</p></div>';$('lines').append(empty)}}
function renderOnline(routes,usage){$('online-section').hidden=false;text('line-count',routes.length);text('online-customer',state.online_service.customer?.display_name||'已开户注册');text('online-used',bytes(usage.used_bytes));text('online-remaining',usage.remaining_bytes==null?'不限额':bytes(usage.remaining_bytes));text('online-period',date(usage.period_end));const lease=state.online_service.lease;text('expires',date(lease?.expires_at));text('online-lease',lease?`当前租约：${lease.id}\n到期：${date(lease.expires_at)}`:'当前未选择源网节点');$('online-lines').replaceChildren();for(const line of routes){const article=document.createElement('article');article.className='card line-card';const content=document.createElement('div');content.className='card-content card-content-padding';const title=document.createElement('h2');title.textContent=line.name;const detail=document.createElement('p');detail.className='mono wrap';detail.textContent=`校园网接入点：${line.endpoint}\n节点编号：${line.id}`;const actions=document.createElement('div');actions.className='action-row';actions.append(button('选择此源网节点','button-fill',()=>run(async()=>{await api('online/lease',{grant_id:line.id});notice('源网节点已选择，租约已经下发。');await refresh();}),!!lease),button('释放当前节点','button-outline color-red',()=>run(async()=>{await api('online/lease/release',{});notice('当前源网节点租约已释放。');await refresh();}),!lease));content.append(title,detail,actions);article.append(content);$('online-lines').append(article)}if(!routes.length){const empty=document.createElement('article');empty.className='card';empty.innerHTML='<div class="card-content card-content-padding"><p>服务端当前没有向此设备授权源网节点。</p></div>';$('online-lines').append(empty)}}
async function refreshOnline(){if(!state.online_service?.configured)return;$('online-section').hidden=false;try{const catalog=await api('online/subscription');state.online_service.customer=catalog.customer||{};renderOnline(catalog.routes||[],catalog.usage||{})}catch(error){notice(error.message,true)}}
async function refresh(){state=await api('state');text('identity',`${state.hostname} · 客户纯享版 v${state.version}`);text('platform',state.platform);text('line-count',state.online_service?.configured?'在线':state.lines.length);text('expires',date(state.subscription_expires_at));const connected=state.lines.find(x=>x.connected);text('status-title',connected?`正在使用 ${connected.name}`:state.online_service?.configured?'商业订阅已连接':state.error?'订阅需要处理':'当前未借网');text('status-detail',connected?'隧道已经启动；可继续查看握手、流量和线路状态。':state.online_service?.configured?'已连接校园网订阅服务，可以选择获授权的源网节点。':state.error||'粘贴管理员提供的订阅地址。');$('status-dot').className='status-dot '+(connected||state.online_service?.configured?'ok':state.error?'warn':'');const sub=state.subscription||{};const online=state.online_service;const summary=online?.configured?`服务地址：${online.provider||'校园网服务'}\n客户编号：${online.customer_id}\n设备编号：${online.device_id}`:`${sub.configured?'服务域名：'+(sub.provider||'尚未更新'):'尚未配置订阅'}\n当前设备编号：${sub.device_id||'读取失败'}\n签名公钥指纹：${sub.key_fingerprint||'尚未读取'}`;text('subscription-summary',summary);renderLines(state.lines);await refreshOnline()}
$('subscription-form').onsubmit=event=>{event.preventDefault();run(async()=>{const url=$('subscription-url').value.trim();if(url.includes('#enroll=')){await api('online/enroll',{url});notice('商业订阅已读取并绑定到本机。')}else{await api('subscription',{url});notice('签名订阅已保存并验证。')}$('subscription-url').value='';await refresh();});};
$('update').onclick=()=>run(async()=>{if(!state.online_service?.configured)await api('subscription/update',{});notice('订阅状态已更新。');await refresh();});
$('remove').onclick=()=>run(async()=>{if(state&&state.lines.some(x=>x.connected))throw new Error('请先退出正在使用的借网线路');if(state.online_service?.configured)await api('online/remove',{});else await api('subscription/remove',{});$('online-section').hidden=true;notice('本机订阅已移除。');await refresh();});
$('refresh').onclick=()=>run(refresh);run(refresh);setInterval(()=>{if(!document.hidden)run(refresh)},5000);
